name: LavaRises
version: 1.0
main: dev.acronical.lavarises.LavaRises
api-version: '1.20'
commands:
  lavarise:
    description: Raises the lava level
    usage: /<command> <amount>
    permission: lavarises.lavarise
depend:
  - FastAsyncWorldEdit