name: LavaRises
author: Acronical
website: https://acronical.pages.dev
description: A customisable plugin that raises the lava level based on an area you define and the amount you specify.
default-permission: op
permissions:
    lavarises.lavarise:
        description: Allows the player to raise the lava level
        default: op
    lavarises.initlava:
        description: Allows the player to initialize the lava level
        default: op
version: 1.0
main: dev.acronical.lavarises.LavaRises
api-version: '1.20'
commands:
  lavarise:
    description: Raises the lava level
    usage: /<command> <amount>
    permission: lavarises.lavarise
    aliases:
      - raiselava
  initlava:
    description: Initializes the lava level
    usage: /<command> <length> <width> [originx] [originz]
    permission: lavarises.initlava
    aliases:
      - initlava
depend:
  - FastAsyncWorldEdit