name: LavaRises
version: 1.0
main: dev.acronical.lavarises.LavaRises
api-version: '1.20'
commands:
  lavarise:
    description: Raises the lava level
    usage: /<command> <amount>
    permission: lavarises.lavarise
    aliases:
      - raiselava
  initlava:
    description: Initializes the lava level
    usage: /<command> <length> <width> [originx] [originz]
    permission: lavarises.initlava
    aliases:
      - initlava
depend:
  - FastAsyncWorldEdit